import express from 'express';
import crypto from 'crypto';
import { v4 as uuidv4 } from 'uuid';
import os from 'os';
import path from 'path';
import fs from 'fs';
import type { CodexJob, JobRecord } from './types.js';
import { cloneRepo, createBranch, commitAndPush, createPR } from './github.js';
import { runCodexFix } from './codex-runner.js';

// crypto is a built-in — imported above to keep the import explicit.
void crypto; // satisfy "unused import" linters; used indirectly via validateSecret

const app = express();
app.use(express.json({ limit: '1mb' }));

// In-memory job store (sufficient for demo)
const jobs = new Map<string, JobRecord>();

/** Validate the shared secret using timing-safe comparison. */
function validateSecret(req: express.Request): boolean {
  const provided = req.headers['x-codex-worker-secret'];
  const expected = process.env.CODEX_WORKER_SECRET;
  if (!provided || !expected || typeof provided !== 'string') return false;
  if (provided.length !== expected.length) return false;
  try {
    return crypto.timingSafeEqual(Buffer.from(provided), Buffer.from(expected));
  } catch {
    return false;
  }
}

app.get('/health', (_req, res) => {
  res.json({ status: 'ok', jobs: jobs.size });
});

app.get('/jobs/:id', (req, res) => {
  if (!validateSecret(req)) {
    res.status(401).json({ error: 'Unauthorized' });
    return;
  }
  const job = jobs.get(req.params.id);
  if (!job) {
    res.status(404).json({ error: 'Not found' });
    return;
  }
  res.json(job);
});

app.post('/jobs', (req, res) => {
  if (!validateSecret(req)) {
    res.status(401).json({ error: 'Unauthorized' });
    return;
  }

  const body = req.body as CodexJob;
  if (!body.ticketId || !body.repoUrl || !body.findings) {
    res.status(400).json({ error: 'Missing required fields' });
    return;
  }

  // Validate ticketId is alphanumeric + hyphens only
  if (!/^[A-Za-z0-9-]+$/.test(body.ticketId)) {
    res.status(400).json({ error: 'Invalid ticketId format' });
    return;
  }

  const jobId = uuidv4();
  const branchName = `fix/${body.ticketId}`;
  const record: JobRecord = {
    id: jobId,
    ticketId: body.ticketId,
    status: 'pending',
    branchName,
    createdAt: new Date(),
    updatedAt: new Date(),
  };
  jobs.set(jobId, record);

  // Return immediately, then process asynchronously
  res.status(202).json({ jobId, status: 'pending' });

  processJob(jobId, body, record, branchName).catch((err: unknown) => {
    console.error(`Job ${jobId} failed:`, err);
    record.status = 'failed';
    record.error = err instanceof Error ? err.message : String(err);
    record.updatedAt = new Date();
  });
});

async function processJob(
  jobId: string,
  job: CodexJob,
  record: JobRecord,
  branchName: string,
): Promise<void> {
  const workDir = path.join(os.tmpdir(), `codex-job-${jobId}`);

  try {
    record.status = 'running';
    record.updatedAt = new Date();

    // 1. Clone the repo
    cloneRepo(job.repoUrl, workDir);

    // 2. Create fix branch
    createBranch(workDir, branchName, job.branchBase);

    // 3. Run Codex to apply the fix
    runCodexFix(workDir, job);

    // 4. Commit and push
    const commitMsg = `fix: ${job.ticketTitle} [ticket:${job.ticketId}]`;
    commitAndPush(workDir, branchName, commitMsg);

    // 5. Create PR
    const prBody = [
      `## Fix for ${job.ticketId}`,
      '',
      `**Bug location:** \`${job.findings.file}\` line ${job.findings.line}`,
      '',
      `**Root cause:** ${job.findings.description}`,
      '',
      `**Fix applied:** ${job.findings.fix}`,
      '',
      `---`,
      `_Automated fix generated by Codex CLI via SDLC Agent Harness_`,
      `Notion ticket: ${job.ticketId}`,
    ].join('\n');

    const prUrl = await createPR(
      workDir,
      `fix: ${job.ticketTitle}`,
      prBody,
      branchName,
      job.branchBase,
    );

    record.status = 'done';
    record.prUrl = prUrl;
    record.updatedAt = new Date();

    console.log(`Job ${jobId} completed. PR: ${prUrl}`);
  } finally {
    // Clean up work directory regardless of success or failure
    try {
      fs.rmSync(workDir, { recursive: true, force: true });
    } catch {
      // ignore cleanup errors
    }
  }
}

const PORT = process.env.PORT ?? 3001;
app.listen(PORT, () => {
  console.log(`Codex worker listening on port ${PORT}`);
});
